/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BackToTop: typeof import('./../components/BackToTop.vue')['default']
    BlogList: typeof import('./../components/BlogList.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    FeaturedCarousel: typeof import('./../components/FeaturedCarousel.vue')['default']
    Footer: typeof import('./../components/Footer.vue')['default']
    HeaderNav: typeof import('./../components/HeaderNav.vue')['default']
    Heo: typeof import('./../components/Heo.vue')['default']
    LatestPosts: typeof import('./../components/LatestPosts.vue')['default']
    LinksSection: typeof import('./../components/LinksSection.vue')['default']
    MediaSection: typeof import('./../components/MediaSection.vue')['default']
    ProjectShow: typeof import('./../components/ProjectShow.vue')['default']
    ProjectShowThird: typeof import('./../components/ProjectShowThird.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollReveal: typeof import('./../components/ScrollReveal.vue')['default']
    SponsorsSection: typeof import('./../components/SponsorsSection.vue')['default']
    ToolsSection: typeof import('./../components/ToolsSection.vue')['default']
  }
}
